# Site
name: 'Autonomous Driving Lab'
description: 'autonomous driving technology  laboratory'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
disqus: 'autonomousdrivinglab'
email: 'autonomousdriving@163.com'
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    lyf:
      name:           lyf
      site:           https://github.com/liuyf5231
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am lyf "
      email:          liuyf5231@gmail.com
      twitter:        https://twitter.com/yifeiliu13
      zhihu:          liuyf5231 # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID    : 79d17be117fbddf14aa2
  clientSecret: 8423d9fc9183a754eaea0cf23b2317d5f12c2b8c
  repository  : autonomousdrivinglab.github.io
  owner       : autonomousdrivinglab
  admin:
    - autonomousdrivinglab

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: lyf
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]